### PUBLIC
GET http://localhost:8080/testPublic

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Answer not expected");
    });
%}

###
GET http://localhost:8080/testPublic
Authorization: Basic aaa bbb

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Answer not expected");
    });
%}

### PRIVATE
GET http://localhost:8080/testPrivate

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 401, "Answer not expected");
    });
%}

###
GET http://localhost:8080/testPrivate
Authorization: Basic aaa bbb

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Answer not expected");
    });
%}